### ISSUE TITLE
Cannot add users to new groups

### ISSUE THREAD

**Issue by Kev-kutkin** [Nillth/Qlik-NPrinting-CLI#4]
I am using NPrinting May 2021 version. I have one hundred new Nprinting (NP) users that I would like to add them into a specific new group. They have been created by previous NP admin by the time I would like to perform this procedure.  

I have tried both REST API methods, but all failed to get the web console to reflect the addition outcome. I attached three pictures that shows the scripts used and their errors. To explain more, I could not determine how the parameters are used because the documentation is not clear to me as shown below. Please advise.

Question one:
The Request Parameter of the NP's User section is not clear. What are required under the groupids as shown in the picture below? This section of the documentation needs update because some Request Parameter of other APIs are clearly hyperlinked. 
![missing_link](https://user-images.githubusercontent.com/25189239/171305584-3ab2144b-bb6d-4116-8bfd-0ceb324caff9.jpg)

Question two:
Assuming the groupids above are linked to this 'Groups' section, but all parameters of the Groups are optional. So, what is to be used if this is the case?
![api_arameter_optional](https://user-images.githubusercontent.com/25189239/171304619-0fae72fe-6741-4ebd-be58-9c9b7f3e753c.jpg)

Question three:
1. Using Invoke-RestMethod, but the -Body could not be read correctly. 
<img width="731" alt="np1_error" src="https://user-images.githubusercontent.com/25189239/171304139-6ff4ef3f-c6eb-41de-abe2-ffc364100e61.png">

2. Using Invoke-RestMethod again, but the -Body could not be read correctly.  
<img width="917" alt="np2_error" src="https://user-images.githubusercontent.com/25189239/171304303-b859f950-1f06-41cc-9145-1137bd9cbb99.png">

3. Using Invoke-NPRequest, but the -Data could not be read correctly.
<img width="740" alt="np3_error" src="https://user-images.githubusercontent.com/25189239/171305840-b35c141e-dcfe-4d71-bfff-8ff535928717.png">

Can I get advice on the parameter and its syntax required to use these two API methods correctly please?

Thank you.

**Comment by Nillth** [comment]
You were close, but rather than providing a "id" parameter on the json body you need just an array of ID'
![image](https://user-images.githubusercontent.com/22066262/172281621-4adc9289-959a-416f-83c6-41da3e6a1227.png)

In PowerShell when Piping a single object array to the `ConvertTo-Json` function it outputs just a Json Object, not a Json Array
![image](https://user-images.githubusercontent.com/22066262/172281043-f8d73692-5fe6-484d-9672-957706f5163d.png)

Ironically if you had had more than one group in the array piping to `ConvertTo-Json` would have provided the required Json Array
![image](https://user-images.githubusercontent.com/22066262/172282252-9f76a935-dc7c-4111-919f-b4d7698e7c59.png)


For type consistent results you need to use `ConvertTo-Json -InputObject` which will output a Json Array if the input is a Single Object Array, or Multiple Object Array
![image](https://user-images.githubusercontent.com/22066262/172281107-01be93c2-8d12-4bdd-87a4-1674f4dcd598.png)

The single object Json Array can then be used on the data parameter of `Invoke-NPRequest`
![image](https://user-images.githubusercontent.com/22066262/172281438-6147c653-8232-4dd9-8a9e-abbb5c4c2495.png)

For multiple groups it may look like this
![image](https://user-images.githubusercontent.com/22066262/172281397-781337af-af4b-4258-82b8-97a550052937.png)
